### ISSUE TITLE
Support for custom fields

### ISSUE THREAD

**Issue by drumlinish** [ctfer-io/go-ctfd#114]
Is there a way to call for example `client.PostChallenges` with custom challenge fields?

**Comment by pandatix** [comment]
Hello, no there is not.

Nevertheless there is a way to extend the API for what I guess is your use case: a plugin.
In that case, I just opened PR #115 to better explain it :smile:

**Comment by pandatix** [comment]
For a more realistic use case, @yyewolf did something similar [here in `i`](https://github.com/4T-24/i/blob/main/internal/ctf/operations.go).
